name: CD

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build e publicar
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m build
        twine upload dist/*